name = "pishvabot"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "pishvabot_db"
database_id = "39675e9e-1442-4444-9032-b19fd80f2ca7" # آیدی دیتابیس Cloudflare خود را قرار دهید

[vars]
TELEGRAM_BOT_TOKEN = "8820980497:AAH7pJaEBk9gOYBAPllruazDLDLWlPW5hrI" # توکن ربات تلگرام
